### PR TITLE
Manual edits to integrated_to_foursquare.json mapping to reflect changes to be made to Categories Postgres DB

### PR DESCRIPTION
**Pull request by neeti-ganjur**
As per the requirements of this [ticket](https://foursquare.atlassian.net/browse/PLAC-15286). Originally we had assumed that the the taxonomy writer [script](https://github.com/Factual/places-categories/tree/develop/scripts/taxonomy) would update taxonomy files, mapping files as well as the categories postgres db. This turned out to be only partially true - the script only updates taxonomy files in scarecrow-rules, scarecrow-landfill, places-categories, and places repos, but does not handle category mapping updates (i.e. does not update mapping files in places/categories/integrated_places_files). As the scope of the current ticket is directly impacting Oakley (due to the sunglasses store mapping outlined in the ticket), we thought it would be best to manually update the mapping files for the current ticket. I have created a follow-up ticket for the next sprint to modify the taxonomy script to update category mappings: https://foursquare.atlassian.net/browse/PLAC-15483

### CODE REVIEW

**Review by aetropolski — APPROVED** [review]
lgtm! Make sure to update the production db as well after you merge. There's a monthly job that dumps that postgres table to s3 which we might want to run manually as well, I'll have to look into it and see when the next run is.

**Comment by neeti-ganjur** [comment]
ran the script to update the production db! Any updates on how to dump the table to s3?

**Review by SteveVitali — COMMENTED** [review]
Just stumbled on this old PR. Do we have a ticket in Jira currently to update the "taxonomy writer" script linked in this PR so that it also writes these mapper files in Factual/places in addition to the taxonomy files?

**Comment by aetropolski** [comment]
> Just stumbled on this old PR. Do we have a ticket in Jira currently to update the "taxonomy writer" script linked in this PR so that it also writes these mapper files in Factual/places in addition to the taxonomy files?

@SteveVitali That ticket does exist, but after further discussions we decided to actually overhaul the way that we store categories altogether. Since we don't plan on doing any further changes until after that, we probably won't need that ticket.

**Pull request merged**
