### PR TITLE
[PLAC-16431] Adding KH,VN,TH,PH,MY,ID translations to integrated_category_taxonomy file

### PR DESCRIPTION
**Pull request by neeti-ganjur**
Created and ran a script to take translations attached to this ticket: https://foursquare.atlassian.net/browse/PLAC-16431 and edited integrated_category_taxonomy.json file to add these translated labels.

### CODE REVIEW

**Review by dbortnichak-fs — CHANGES_REQUESTED** [review]
Level 1 category "10000"   "Arts and Entertainment" has no translation while other level 1 categories do.

**Comment by neeti-ganjur** [comment]
> Level 1 category "10000" "Arts and Entertainment" has no translation while other level 1 categories do.

fixed in second commit!

**Comment by neeti-ganjur** [comment]
> > Level 1 category "10000" "Arts and Entertainment" has no translation while other level 1 categories do.
> 
> fixed in second commit! and switched from country code labels to language labels as discussed offline in ticket comments: https://foursquare.atlassian.net/browse/PLAC-16431

**Comment by neeti-ganjur** [comment]
hmm they should all be 1145, I've started to look into what's going on and will push a commit once i've figured out the source.

**Comment by neeti-ganjur** [comment]
I reran the scripts and made some indexing changes that seemed to do the trick and then manually added translated names for the following that did not get picked up by the script:
Heating, Ventilating and Air Conditioning Contractor
Shipping, Freight, and Material Transportation Service
Cafes, Coffee, and Tea Houses
Bubble Tea Shop
Café
Coffee Shop
Tea Room
Pet Café
Ear, Nose and Throat Doctor

**Comment by neeti-ganjur** [comment]
Here is a link the a folder in drive with the python scripts I used and all the processed and raw csv files: https://drive.google.com/drive/folders/16L-j2wklCwv7Fs976iLj-k2W_WfRz4TD?usp=sharing

**Review by dbortnichak-fs — APPROVED** [review]
Yes, counts improved.

**Pull request merged**
